
nodes = {
    c37_client = {
        type = "c37.118"

        in = {
            address = "localhost"
            port = 9991
            idcode = 0xBEEF
        }
    }
}

paths = (
    {
        in = "c37_client"
        hooks = ("print")
    }
)
