
nodes = {
    signal = {
        type = "signal.v2"
        rate = 10000

        in = {
            signals = (
                { name = "freq", signal = "constant", amplitude = 50 },
                { name = "dfreq", signal = "constant", amplitude = 0 },
                { name = "analog", signal = "sine", amplitude = 1000 },
            )

            hooks = ("print")
        }
    }

    c37_server = {
        type = "c37.118"

        out = {
            address = "localhost"
            port = 9991
            idcode = 0xBEEF
            config = {
                time_base = 1000000
                data_rate = 0xFFFF
                pmus = ({
                    stn = "VILLASnode"
                    idcode = 0xBEEF
                    format = 0
                    fnom = 1
                    aninfo = ({
                        chnam = "analog"
                        anunit = 1
                    })
                    cfgcnt = 1
                })
            }
        }
    }
}

paths = (
    {
        in = "signal"
        out = "c37_server"
    }
)
