
nodes = {
    c37_client = {
        type = "c37.118"

        in = {
            address = "134.130.169.66"
            port = 4712
            idcode = 2
        }
    }
}

paths = ({
    in = "c37_client",
    hooks = ("print")
})
