
nodes = {
    signal = {
        type = "signal.v2"
        rate = 10

        in = {
            signals = ({
                signal = "sine"
            })

            hooks = ("print")
        }
    }

    c37_server = {
        type = "c37.118"

        out = {
            address = "10.100.2.201"
            port = 9991
            idcode = 0xBEEF

            config = {
                time_base = 1000000
                data_rate = 10
                pmus = ({
                    stn = "VILLASnode"
                    idcode = 0xBEEF
                    format = 0
                    fnom = 50
                    cfgcnt = 1
                })
            }
        }
    }

//    c37_client = {
//        type = "c37.118"
//
//        in = {
//            address = "localhost"
//            port = 9991
//            idcode = 0xBEEF
//        }
//    }
}

paths = (
//    {
//        in = "c37_client"
//        hooks = ("print")
//    },
    {
        in = "signal"
        out = "c37_server"
    }
)
